Activating conda env and running make test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -60,23 +60,9 @@ jobs:
     - uses: conda-incubator/setup-miniconda@v3
       with:
         miniforge-version: latest
-        use-mamba: true
         activate-environment: pypsa-earth
         channel-priority: strict
         conda-remove-defaults: true
-
-    - name: Check environment and snakemake
-      shell: bash -l {0}
-      continue-on-error: true
-      run: |
-        echo ">>> Conda environments"
-        conda info --envs || true
-
-        echo ">>> Where is snakemake"
-        which snakemake || true
-
-        echo ">>> Snakemake version"
-        snakemake --version || true
 
     - name: Cache Conda env
       uses: actions/cache@v4
@@ -92,25 +78,15 @@ jobs:
     - name: Conda list
       run: conda list
 
-    - name: Check Snakemake installation
-      shell: bash -l {0}
-      continue-on-error: true
-      run: |
-        echo ">>> Conda environments"
-        conda info --envs || true
-
-        echo ">>> Where is snakemake"
-        which snakemake || true
-
-        echo ">>> Snakemake version"
-        snakemake --version || true
-
-        echo ">>> Conda list of snakemake"
-        conda list | grep snakemake || true
-
     - name: Run Test
       shell: bash -l {0}
-      run: make test
+      run: |
+        echo ">>> Activating conda env and running make test"
+        source ~/.bashrc
+        conda activate pypsa-earth
+        which snakemake || echo "Snakemake not found"
+        snakemake --version || echo "Snakemake version error"
+        make test
 
     - name: Upload artifacts
       if: always()
